Build script generating files and content

diff --git a/build b/build
--- a/build
+++ b/build
@@ -2,6 +2,22 @@
 
 WORKING_DIR=$PWD
 
-cd .. && mkdir idea_box_exercise && cd idea_box_exercise
-mkdir -p lib/javascripts \
-         lib/css
+cd ..
+if [[ -d "idea_box_exercise" ]]; then
+  echo "ERROR: ${PWD}/idea_box_exercise already exists."
+  echo "Must delete, move or rename this directory in order to generate a blank template."
+  echo "Terminating process."
+  exit 1
+fi
+mkdir idea_box_exercise && cd idea_box_exercise
+mkdir -p src/javascripts \
+         src/css
+
+printf "%s\n" "<!DOCTYPE html>" "<html>" "  <head>" "    <meta charset=\"utf-8\">" "    <title>IdeaBox</title>" "    <link rel=\"stylesheet\" href=\"/css/master.css\">" "    <script defer type=\"text/javascript\" src=\"/bundle.js\"></script>" "  </head>" "  <body>" "    <div id=\"nav\"></div>" "    <div id=\"headline\"></div>" "    <div id=\"idea-form\"></div>" "    <div id=\"idea-list\"></div>" "  </body>" "</html>" > src/index.html
+printf "%s\n" "const $ = require('jquery');" "" "let scope = {" "  username: 'Guest'," "  idea_num: 0" "}" "" "// Insert your code here to complete the necessary features for IdeaBox" "" "// EXAMPLE:" "// \$('#test').on('click', () => {" "//   console.log('Hello World')" "// })" > src/javascripts/main.js
+printf "%s\n" "/* Insert your CSS here */" > src/css/master.css
+printf "%s\n" "### Build ###" "dist/" "" "### Node ###" "# Logs" "logs" "*.logs" "npm-debug.log*" "" "# Dependency directories" "node_modules" "jspm_packages" "" "# Optional npm cache directory" ".npm" > .gitignore
+printf "%s\n" "var path = require(\"path\")," "    express = require(\"express\");" "" "var DIST_DIR = path.join(__dirname, \"dist\")," "    port = 2020," "    app = express();" "" "//Serving the files on the dist folder" "app.use(express.static(DIST_DIR));" "" "//Send index.html when the user access the web" "app.get(\"*\", function (req, res) {" "  res.sendFile(path.join(DIST_DIR, \"index.html\"));" "})" "" "app.listen(port, function(){" "  console.log('IdeaBox application starting up on http://localhost:' + port);" "});" > app.js
+printf "%s\n" "{" "  \"name\": \"IdeaBox\"," "  \"version\": \"0.0.1\"," "  \"description\": \"IdeaBox using jquery for mentoring Turing FEE\"," "  \"main\": \"main.js\"," "  \"dependencies\": {" "    \"express\": \"^4.14.0\"," "    \"jquery\": \"^3.2.1\"" "  }," "  \"scripts\": {" "    \"start\": \"node app.js\"," "    \"build\": \"./node_modules/webpack/bin/webpack.js && cp ./src/index.html ./dist && cp -r ./src/css ./dist && npm start\"" "  }," "  \"author\": \"\"," "  \"license\": \"ISC\"," "  \"repository\": {" "    \"type\": \"git\"," "    \"url\": \"git+https://github.com/rdavid1099/idea_box_mentoring\"" "  }," "  \"homepage\": \"https://github.com/rdavid1099/idea_box_mentoring\"," "  \"devDependencies\": {" "    \"webpack\": \"^3.10.0\"" "  }" "}" > package.json
+printf "%s\n" "# IdeaBox Exercise" "## Created by Ryan Workman for Mentoring Turing Students" "Clone down this repo and run \`npm install && npm run build\` to launch the application." > README.md
+printf "%s\n" "var path = require('path');" "" "var DIST_DIR   = path.join(__dirname, \"dist\")," "    CLIENT_DIR = path.join(__dirname, \"src\");" "" "module.exports = {" "  context: CLIENT_DIR," "  entry: \"./javascripts/main\"," "  output: {" "    path: DIST_DIR," "    filename: \"bundle.js\"" "  }," "  resolve: {" "    extensions: ['.js']" "  }" "}" > webpack.config.js
